# ===== SITE SETTINGS =====
title: "Portfolio-Leah Pettway"                          
title_separator: "-"
name: "Leah Pettway"                           
description: "Portfolio of Academic research and applied projects"   
url: "https://leah-Pettway.github.io"       
baseurl: ""
locale: "en-US"

# ===== THEME =====
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"            

# ===== BUILD SETTINGS =====
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# ===== AUTHOR sidebar=====
author:
  name: "Leah Pettway"                         
  avatar: "/assets/images/headshot.jpg"     
  bio: "A recent graduate from UCSB interested in spatial data applications in the Environmental and urban planning fields."   
  location: "Long Beach, CA"                 
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:leahlamarre@gmail.com"           
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/leahpettway"   
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/leah-Pettway"       

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/leah-Pettway"

# ===== COLLECTIONS  =====
collections:
  projects:
    output: true
    permalink: /projects/:path/

# ===== DEFAULTS =====
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  # _projects collection
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      share: true
      related: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
